### ISSUE TITLE
Gravar vídeo da apresentação 2

### ISSUE THREAD

**Issue by g-assismoraes** [RodolphoVSantoro/j-xadrez#64]

**Comment by PedroAlmeida08** [comment]
Roteiro do vídeo de acordo com as especificações em http://www.ic.uff.br/~leomurta/courses/2023.1/es2.html:

1. Como está sendo usado controle de versões (e.g., Git)?
    GitHub Desktop + VS Code com Git integrado

2. Como está sendo feito o controle de modificações no projeto (e.g., GitHub Issues)?
    As modificações tem sido comunicadas/solicitadas aos outros membros do grupo das seguintes formas:
        - Pessoalmente;
        - Aplicativo de mensagens instantâneas;
        - Comentários em pull requests; (mostrar)
        - GitHub Issues; (mostrar)

3. Qual estratégia de ramificação foi adotada?
    Para cada novo grupo de funcionalidades do código deve ser criado um novo ramo. Quando a implementação estiver completa, deverá ser aberto um pull request que, mediante aprovação, será integrado à raiz do projeto (main).

4. Apresentar o conteúdo do repositório;

5. GitHub Actions; (mostrar)

5. Gráfico de Burndown dentro de cada iteração; (mostrar)

6. Análise de Valor Agregado ao final de cada iteração; (mostrar)

7. Execução do código; (mostrar)

8. Fornecer endereço do repositório de controle de versões e de controle de modificações.
